services:
  db_test:
    image: postgres
    container_name: db_test
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  node-app:
    container_name: node-app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env.test
