name: Deploy on Heroku
on: 
  push: 
    branch: 
    - main
  
  jobs:
    Heroku_deplot,
    runs-on: ubuntu_latest
    steps: 
      - name: Check out repository code
        users: actions/checkout@v3
        users: akhileshns/heroku-deploy@v3.12.1
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main"
