name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "seravate"
          envkey_POSTGRES_DB: "actions_test"
          envkey_DATABASE_URL: "postgres://postgres:seravate@db_actions_test:5432/actions_test"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose_tests.yml run node_app_action npm run test
      - name: Build
        run: npm i && npm run build